<?php

namespace Tests\Feature;

use App\Models\AcademicYear;
use App\Models\Application;
use App\Models\Course;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Tests\TestCase;

class ApplicantImportCustomNumberTest extends TestCase
{
    use RefreshDatabase;

    private User $admin;
    private AcademicYear $academicYear;
    private Course $course;

    protected function setUp(): void
    {
        parent::setUp();

        $this->admin = User::factory()->create();
        $this->admin->assignRole('super_admin');

        $this->academicYear = AcademicYear::factory()->create([
            'academic_year' => '2026-2027',
            'semester' => 1,
        ]);

        $this->course = Course::factory()->create(['code' => 'BSCS', 'is_active' => true]);
    }

    private function makeCsv(array $headers, array $rows): UploadedFile
    {
        $content = implode(',', $headers)."\n";
        foreach ($rows as $row) {
            $content .= implode(',', $row)."\n";
        }

        $path = tempnam(sys_get_temp_dir(), 'csv');
        file_put_contents($path, $content);

        return new UploadedFile($path, 'test.csv', 'text/csv', null, true);
    }

    private function validRecord(array $overrides = []): array
    {
        return array_merge([
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
            'birthdate' => '2000-01-15',
            'sex' => 'Male',
            'course_preference_1' => $this->course->code,
        ], $overrides);
    }

    public function test_import_with_valid_custom_applicant_number(): void
    {
        $file = $this->makeCsv(
            ['first_name', 'last_name', 'email', 'birthdate', 'sex', 'course_preference_1', 'applicant_number'],
            [['John', 'Doe', 'john@example.com', '2000-01-15', 'Male', 'BSCS', 'CUSTOM-12345']]
        );

        $response = $this->actingAs($this->admin)
            ->post('/admin/applications/import/preview', [
                'file' => $file,
                'academic_year_id' => $this->academicYear->id,
            ]);

        $response->assertOk();
        $response->assertInertia(fn ($page) => $page
            ->component('Admin/Applications/ImportPreview')
            ->where('validCount', 1)
        );

        // Confirm import
        $records = [
            $this->validRecord([
                'email' => 'john@example.com',
                'applicant_number' => 'CUSTOM-12345',
            ]),
        ];

        $response = $this->actingAs($this->admin)
            ->withSession([
                'import_records' => $records,
                'import_academic_year_id' => $this->academicYear->id,
            ])
            ->post('/admin/applications/import/confirm', [
                'selected_ids' => [0],
            ]);

        $response->assertRedirect();

        $this->assertDatabaseHas('applications', [
            'email' => 'john@example.com',
            'reference_number' => 'CUSTOM-12345',
            'academic_year_id' => $this->academicYear->id,
        ]);
    }

    public function test_import_falls_back_to_autogenerated_number_when_omitted(): void
    {
        $file = $this->makeCsv(
            ['first_name', 'last_name', 'email', 'birthdate', 'sex', 'course_preference_1'],
            [['John', 'Doe', 'john@example.com', '2000-01-15', 'Male', 'BSCS']]
        );

        $response = $this->actingAs($this->admin)
            ->post('/admin/applications/import/preview', [
                'file' => $file,
                'academic_year_id' => $this->academicYear->id,
            ]);

        $response->assertOk();
        $response->assertInertia(fn ($page) => $page
            ->component('Admin/Applications/ImportPreview')
            ->where('validCount', 1)
        );

        // Confirm import
        $records = [
            $this->validRecord([
                'email' => 'john@example.com',
                // applicant_number is omitted
            ]),
        ];

        $response = $this->actingAs($this->admin)
            ->withSession([
                'import_records' => $records,
                'import_academic_year_id' => $this->academicYear->id,
            ])
            ->post('/admin/applications/import/confirm', [
                'selected_ids' => [0],
            ]);

        $response->assertRedirect();

        $application = Application::where('email', 'john@example.com')->first();
        $this->assertNotNull($application);
        $this->assertNotEmpty($application->reference_number);
        // The auto-generated reference number should be formatted (e.g., contains academic year details or follows the standard format)
        $this->assertStringContainsString('2026', $application->reference_number);
    }

    public function test_import_fails_validation_when_custom_number_exceeds_length_limit(): void
    {
        // Custom applicant number > 20 characters (21 characters: CUSTOM-12345678901234)
        $file = $this->makeCsv(
            ['first_name', 'last_name', 'email', 'birthdate', 'sex', 'course_preference_1', 'applicant_number'],
            [['John', 'Doe', 'john@example.com', '2000-01-15', 'Male', 'BSCS', 'CUSTOM-12345678901234']]
        );

        $response = $this->actingAs($this->admin)
            ->post('/admin/applications/import/preview', [
                'file' => $file,
                'academic_year_id' => $this->academicYear->id,
            ]);

        $response->assertOk();
        $response->assertInertia(fn ($page) => $page
            ->component('Admin/Applications/ImportPreview')
            ->where('validCount', 0)
        );
    }

    public function test_import_fails_validation_when_custom_number_already_exists_in_database(): void
    {
        // Create an existing application with the target reference_number
        Application::factory()->create([
            'reference_number' => 'CUSTOM-12345',
            'academic_year_id' => $this->academicYear->id,
        ]);

        $file = $this->makeCsv(
            ['first_name', 'last_name', 'email', 'birthdate', 'sex', 'course_preference_1', 'applicant_number'],
            [['John', 'Doe', 'john@example.com', '2000-01-15', 'Male', 'BSCS', 'CUSTOM-12345']]
        );

        $response = $this->actingAs($this->admin)
            ->post('/admin/applications/import/preview', [
                'file' => $file,
                'academic_year_id' => $this->academicYear->id,
            ]);

        $response->assertOk();
        $response->assertInertia(fn ($page) => $page
            ->component('Admin/Applications/ImportPreview')
            ->where('validCount', 0)
        );
    }

    public function test_import_fails_validation_when_custom_number_is_duplicated_in_import_file(): void
    {
        $file = $this->makeCsv(
            ['first_name', 'last_name', 'email', 'birthdate', 'sex', 'course_preference_1', 'applicant_number'],
            [
                ['John', 'Doe', 'john@example.com', '2000-01-15', 'Male', 'BSCS', 'CUSTOM-12345'],
                ['Jane', 'Smith', 'jane@example.com', '2000-02-15', 'Female', 'BSCS', 'CUSTOM-12345']
            ]
        );

        $response = $this->actingAs($this->admin)
            ->post('/admin/applications/import/preview', [
                'file' => $file,
                'academic_year_id' => $this->academicYear->id,
            ]);

        $response->assertOk();
        $response->assertInertia(fn ($page) => $page
            ->component('Admin/Applications/ImportPreview')
            ->where('validCount', 1) // One should be valid, the other invalid (duplicate)
        );
    }
}
